#pragma once

#include <string>
#include <vector>
#include <cstdint>
#include <fstream>

#include "edasm/assembler/symbol_table.hpp"

namespace edasm {

// Listing file generator (from ASM1.S and ASM2.S listing logic)
class ListingGenerator {
  public:
    struct ListingLine {
        int line_number{0};
        uint16_t address{0};
        std::vector<uint8_t> bytes;  // Generated bytes for this line
        std::string source_line;     // Original source text
        bool has_address{false};     // Whether this line generates code
    };

    struct Options {
        bool include_symbols = true;  // Include symbol table at end
        bool sort_by_value = false;   // Sort symbols by value (default: by name)
        int symbol_columns = 4;       // 2, 4, or 6 columns (from ASM1.S)
        bool line_numbers_bcd = false; // Use BCD format for line numbers
    };

    ListingGenerator(const Options& opts);

    // Add a line to the listing
    void add_line(const ListingLine& line);

    // Set symbol table for inclusion in listing
    void set_symbol_table(const SymbolTable& symbols);

    // Write listing to file
    bool write_to_file(const std::string& filename);

    // Get listing as string
    std::string to_string() const;

  private:
    Options options_;
    std::vector<ListingLine> lines_;
    const SymbolTable* symbols_{nullptr};

    // Format a single listing line (from ASM2.S)
    std::string format_listing_line(const ListingLine& line) const;

    // Format line number (decimal or BCD)
    std::string format_line_number(int line_num) const;

    // Format address (hex with $ prefix)
    std::string format_address(uint16_t addr) const;

    // Format bytes (hex dump)
    std::string format_bytes(const std::vector<uint8_t>& bytes, size_t max_bytes = 3) const;

    // Generate symbol table section (from ASM1.S DoPass3)
    std::string generate_symbol_table() const;

    // Format symbol table in columns
    std::string format_symbols_in_columns(const std::vector<Symbol>& symbols, int columns) const;

    // Format a single symbol entry
    std::string format_symbol(const Symbol& sym) const;
};

} // namespace edasm
